version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: hintoz-dozzle_web_1
      APP_PORT: 8080

  web:
    image: amir20/dozzle:v10.7.4@sha256:068025ea622a1ce3e343a138dd9a962429b5187a133aca301bb4991fe7d2b708
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure