version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: hintoz-dozzle_web_1
      APP_PORT: 8080

  web:
    image: amir20/dozzle:v10.6.13@sha256:16bf0908398a5a63d9e2ee3450982152cca1ea99d7f551957c4848ec34cdc4b9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure